In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

#Function that takes in the stock ticker as a string and gives the income statement data from YahooFinance

def income_statement_maker(ticker):
    
    income_statement_dict={}

    url='https://finance.yahoo.com/quote/{}/financials?p={}'.format(ticker,ticker)
    income_statement={}
    table_title={}

    headers = {'User-Agent' : 'Safari/19616.1.24.11.3'}
    page=requests.get(url,headers=headers)
    page_content=page.content
    soup=BeautifulSoup(page_content,'html.parser')
    tabl=soup.find_all('div',{'class':'M(0) Whs(n) BdEnd Bdc($seperatorColor) D(itb)'})
    for t in tabl:
        heading=soup.find_all('div',{'class':'D(tbr) C($primaryColor)'})
        for top_row in heading:
            table_title[top_row.get_text(separator="|").split("|")[0]] = top_row.get_text(separator="|").split("|")[1:]
        rows=soup.find_all('div',{'class' : "D(tbr) fi-row Bgc($hoverBgColor):h"})
        for row in rows:
            income_statement[row.get_text(separator="|").split("|")[0]]=row.get_text(separator="|").split("|")[1:]
    temp=pd.DataFrame(income_statement).T
    temp.columns=table_title['Breakdown']
    income_statement_dict[ticker]=temp
    
    #Converting string objects to numerical values
    
    for col in income_statement_dict[ticker].columns:
        income_statement_dict[ticker][col]=income_statement_dict[ticker][col].str.replace(',|-','')
        income_statement_dict[ticker][col]=pd.to_numeric(income_statement_dict[ticker][col],errors='coerce')
    
    return(income_statement_dict[ticker])

#Function that takes in the stock ticker as a string and gives the balance sheet data from YahooFinance

def balance_sheet_maker(ticker):  
    
    balance_sheet_dict={}
    
    url='https://finance.yahoo.com/quote/{}/balance-sheet?p={}'.format(ticker,ticker)
    balance_sheet={}
    table_title={}
    
    headers = {'User-Agent' : 'Safari/19616.1.24.11.3'}
    page=requests.get(url,headers=headers)
    page_content=page.content
    soup=BeautifulSoup(page_content,'html.parser')
    tabl=soup.find_all('div',{'class':'M(0) Whs(n) BdEnd Bdc($seperatorColor) D(itb)'})
    for t in tabl:
        heading=soup.find_all('div',{'class':'D(tbr) C($primaryColor)'})
        for top_row in heading:
            table_title[top_row.get_text(separator="|").split("|")[0]] = top_row.get_text(separator="|").split("|")[1:]
        rows=soup.find_all('div',{'class' : "D(tbr) fi-row Bgc($hoverBgColor):h"})
        for row in rows:
            balance_sheet[row.get_text(separator="|").split("|")[0]]=row.get_text(separator="|").split("|")[1:]
    temp=pd.DataFrame(balance_sheet).T
    temp.columns=table_title['Breakdown']
    balance_sheet_dict[ticker]=temp
    
    #Converting string objects to numerical values
    
    for col in balance_sheet_dict[ticker].columns:
        balance_sheet_dict[ticker][col]=balance_sheet_dict[ticker][col].str.replace(',|-','')
        balance_sheet_dict[ticker][col]=pd.to_numeric(balance_sheet_dict[ticker][col],errors='coerce')
    
    return(balance_sheet_dict[ticker])

#Function that takes in the stock ticker as a string and gives the cashflow data from YahooFinance
    
def cashflow_statement_maker(ticker):
    
    cashflow_dict={}
    
    url='https://finance.yahoo.com/quote/{}/cash-flow?p={}'.format(ticker,ticker)
    cashflow={}
    table_title={}
    
    headers = {'User-Agent' : 'Safari/19616.1.24.11.3'}
    page=requests.get(url,headers=headers)
    page_content=page.content
    soup=BeautifulSoup(page_content,'html.parser')
    tabl=soup.find_all('div',{'class':'M(0) Whs(n) BdEnd Bdc($seperatorColor) D(itb)'})
    for t in tabl:
        heading=soup.find_all('div',{'class':'D(tbr) C($primaryColor)'})
        for top_row in heading:
            table_title[top_row.get_text(separator="|").split("|")[0]] = top_row.get_text(separator="|").split("|")[1:]
        rows=soup.find_all('div',{'class' : "D(tbr) fi-row Bgc($hoverBgColor):h"})
        for row in rows:
            cashflow[row.get_text(separator="|").split("|")[0]]=row.get_text(separator="|").split("|")[1:]
    temp=pd.DataFrame(cashflow).T
    temp.columns=table_title['Breakdown']
    cashflow_dict[ticker]=temp
    
    #Converting all the string values to numeric values
   
    for col in cashflow_dict[ticker].columns:
        cashflow_dict[ticker][col]=cashflow_dict[ticker][col].str.replace(',|-','')
        cashflow_dict[ticker][col]=pd.to_numeric(cashflow_dict[ticker][col],errors='coerce')
    
    return(cashflow_dict[ticker])

In [2]:
income_statement_maker('AAPL')

,ttm,9/30/2022,9/30/2021,9/30/2020,9/30/2019
Total Revenue,387537000.0,3.943280e+08,3.658170e+08,2.745150e+08,2.601740e+08
Cost of Revenue,220666000.0,2.235460e+08,2.129810e+08,1.695590e+08,1.617820e+08
Gross Profit,166871000.0,1.707820e+08,1.528360e+08,1.049560e+08,9.839200e+07
Operating Expense,52906000.0,5.134500e+07,4.388700e+07,3.866800e+07,3.446200e+07
Operating Income,113965000.0,1.194370e+08,1.089490e+08,6.628800e+07,6.393000e+07
Net Non Operating Interest Income Expense,197000.0,1.060000e+05,1.980000e+05,8.900000e+05,1.385000e+06
Other Income Expense,283000.0,3.340000e+05,2.580000e+05,8.030000e+05,1.807000e+06
Pretax Income,113485000.0,1.191030e+08,1.092070e+08,6.709100e+07,6.573700e+07
Tax Provision,18314000.0,1.930000e+07,1.452700e+07,9.680000e+06,1.048100e+07
Net Income Common Stockholders,95171000.0,9.980300e+07,9.468000e+07,5.741100e+07,5.525600e+07
Diluted NI Available to Com Stockholders,95171000.0,9.980300e+07,9.468000e+07,5.741100e+07,5.525600e+07
Basic EPS,NaN,6.150000e+00,5.670000e+00,3.310000e+00,2.990000e+00
Diluted EPS,NaN,6.110000e+00,5.610000e+00,3.280000e+00,2.970000e+00
Basic Average Shares,NaN,1.621596e+07,1.670127e+07,1.735212e+07,1.847134e+07
Diluted Average Shares,NaN,1.632582e+07,1.686492e+07,1.752821e+07,1.859565e+07
Total Operating Income as Reported,113965000.0,1.194370e+08,1.089490e+08,6.628800e+07,6.393000e+07
Total Expenses,273572000.0,2.748910e+08,2.568680e+08,2.082270e+08,1.962440e+08
Net Income from Continuing & Discontinued Operation,95171000.0,9.980300e+07,9.468000e+07,5.741100e+07,5.525600e+07
Normalized Income,95171000.0,9.980300e+07,9.468000e+07,5.741100e+07,5.525600e+07
Interest Income,3043000.0,2.825000e+06,2.843000e+06,3.763000e+06,4.961000e+06
Interest Expense,3240000.0,2.931000e+06,2.645000e+06,2.873000e+06,3.576000e+06
Net Interest Income,197000.0,1.060000e+05,1.980000e+05,8.900000e+05,1.385000e+06
EBIT,116725000.0,1.194370e+08,1.089490e+08,6.628800e+07,6.393000e+07
EBITDA,128048000.0,NaN,NaN,NaN,NaN
Reconciled Cost of Revenue,220666000.0,2.235460e+08,2.129810e+08,1.695590e+08,1.617820e+08
Reconciled Depreciation,11323000.0,1.110400e+07,1.128400e+07,1.105600e+07,1.254700e+07
Net Income from Continuing Operation Net Minority Interest,95171000.0,9.980300e+07,9.468000e+07,5.741100e+07,5.525600e+07
Normalized EBITDA,128048000.0,1.305410e+08,1.202330e+08,7.734400e+07,7.647700e+07
Tax Rate for Calcs,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Tax Effect of Unusual Items,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

In [5]:
income_statement_maker('AAPL')

,ttm,9/30/2022,9/30/2021,9/30/2020,9/30/2019
Total Revenue,387537000.0,3.943280e+08,3.658170e+08,2.745150e+08,2.601740e+08
Cost of Revenue,220666000.0,2.235460e+08,2.129810e+08,1.695590e+08,1.617820e+08
Gross Profit,166871000.0,1.707820e+08,1.528360e+08,1.049560e+08,9.839200e+07
Operating Expense,52906000.0,5.134500e+07,4.388700e+07,3.866800e+07,3.446200e+07
Operating Income,113965000.0,1.194370e+08,1.089490e+08,6.628800e+07,6.393000e+07
Net Non Operating Interest Income Expense,197000.0,1.060000e+05,1.980000e+05,8.900000e+05,1.385000e+06
Other Income Expense,283000.0,3.340000e+05,2.580000e+05,8.030000e+05,1.807000e+06
Pretax Income,113485000.0,1.191030e+08,1.092070e+08,6.709100e+07,6.573700e+07
Tax Provision,18314000.0,1.930000e+07,1.452700e+07,9.680000e+06,1.048100e+07
Net Income Common Stockholders,95171000.0,9.980300e+07,9.468000e+07,5.741100e+07,5.525600e+07
Diluted NI Available to Com Stockholders,95171000.0,9.980300e+07,9.468000e+07,5.741100e+07,5.525600e+07
Basic EPS,NaN,6.150000e+00,5.670000e+00,3.310000e+00,2.990000e+00
Diluted EPS,NaN,6.110000e+00,5.610000e+00,3.280000e+00,2.970000e+00
Basic Average Shares,NaN,1.621596e+07,1.670127e+07,1.735212e+07,1.847134e+07
Diluted Average Shares,NaN,1.632582e+07,1.686492e+07,1.752821e+07,1.859565e+07
Total Operating Income as Reported,113965000.0,1.194370e+08,1.089490e+08,6.628800e+07,6.393000e+07
Total Expenses,273572000.0,2.748910e+08,2.568680e+08,2.082270e+08,1.962440e+08
Net Income from Continuing & Discontinued Operation,95171000.0,9.980300e+07,9.468000e+07,5.741100e+07,5.525600e+07
Normalized Income,95171000.0,9.980300e+07,9.468000e+07,5.741100e+07,5.525600e+07
Interest Income,3043000.0,2.825000e+06,2.843000e+06,3.763000e+06,4.961000e+06
Interest Expense,3240000.0,2.931000e+06,2.645000e+06,2.873000e+06,3.576000e+06
Net Interest Income,197000.0,1.060000e+05,1.980000e+05,8.900000e+05,1.385000e+06
EBIT,116725000.0,1.194370e+08,1.089490e+08,6.628800e+07,6.393000e+07
EBITDA,128048000.0,NaN,NaN,NaN,NaN
Reconciled Cost of Revenue,220666000.0,2.235460e+08,2.129810e+08,1.695590e+08,1.617820e+08
Reconciled Depreciation,11323000.0,1.110400e+07,1.128400e+07,1.105600e+07,1.254700e+07
Net Income from Continuing Operation Net Minority Interest,95171000.0,9.980300e+07,9.468000e+07,5.741100e+07,5.525600e+07
Normalized EBITDA,128048000.0,1.305410e+08,1.202330e+08,7.734400e+07,7.647700e+07
Tax Rate for Calcs,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Tax Effect of Unusual Items,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00